#ifndef MYON_FMPLAYER_VERSION_H_INCLUDED
#define MYON_FMPLAYER_VERSION_H_INCLUDED

#define FMPLAYER_VERSION_0 "0"
#define FMPLAYER_VERSION_1 "1"
#define FMPLAYER_VERSION_2 "14"

#define FMPLAYER_VERSION_STR FMPLAYER_VERSION_0 "." FMPLAYER_VERSION_1 "." FMPLAYER_VERSION_2

#endif // MYON_FMPLAYER_VERSION_H_INCLUDED
