static const uint16_t jis2unicode_h[] = {
  0xA1, 0xFF61, // HALFWIDTH IDEOGRAPHIC FULL STOP
  0xA2, 0xFF62, // HALFWIDTH LEFT CORNER BRACKET
  0xA3, 0xFF63, // HALFWIDTH RIGHT CORNER BRACKET
  0xA4, 0xFF64, // HALFWIDTH IDEOGRAPHIC COMMA
  0xA5, 0xFF65, // HALFWIDTH KATAKANA MIDDLE DOT
  0xA6, 0xFF66, // HALFWIDTH KATAKANA LETTER WO
  0xA7, 0xFF67, // HALFWIDTH KATAKANA LETTER SMALL A
  0xA8, 0xFF68, // HALFWIDTH KATAKANA LETTER SMALL I
  0xA9, 0xFF69, // HALFWIDTH KATAKANA LETTER SMALL U
  0xAA, 0xFF6A, // HALFWIDTH KATAKANA LETTER SMALL E
  0xAB, 0xFF6B, // HALFWIDTH KATAKANA LETTER SMALL O
  0xAC, 0xFF6C, // HALFWIDTH KATAKANA LETTER SMALL YA
  0xAD, 0xFF6D, // HALFWIDTH KATAKANA LETTER SMALL YU
  0xAE, 0xFF6E, // HALFWIDTH KATAKANA LETTER SMALL YO
  0xAF, 0xFF6F, // HALFWIDTH KATAKANA LETTER SMALL TU
  0xB0, 0xFF70, // HALFWIDTH KATAKANA-HIRAGANA PROLONGED SOUND MARK
  0xB1, 0xFF71, // HALFWIDTH KATAKANA LETTER A
  0xB2, 0xFF72, // HALFWIDTH KATAKANA LETTER I
  0xB3, 0xFF73, // HALFWIDTH KATAKANA LETTER U
  0xB4, 0xFF74, // HALFWIDTH KATAKANA LETTER E
  0xB5, 0xFF75, // HALFWIDTH KATAKANA LETTER O
  0xB6, 0xFF76, // HALFWIDTH KATAKANA LETTER KA
  0xB7, 0xFF77, // HALFWIDTH KATAKANA LETTER KI
  0xB8, 0xFF78, // HALFWIDTH KATAKANA LETTER KU
  0xB9, 0xFF79, // HALFWIDTH KATAKANA LETTER KE
  0xBA, 0xFF7A, // HALFWIDTH KATAKANA LETTER KO
  0xBB, 0xFF7B, // HALFWIDTH KATAKANA LETTER SA
  0xBC, 0xFF7C, // HALFWIDTH KATAKANA LETTER SI
  0xBD, 0xFF7D, // HALFWIDTH KATAKANA LETTER SU
  0xBE, 0xFF7E, // HALFWIDTH KATAKANA LETTER SE
  0xBF, 0xFF7F, // HALFWIDTH KATAKANA LETTER SO
  0xC0, 0xFF80, // HALFWIDTH KATAKANA LETTER TA
  0xC1, 0xFF81, // HALFWIDTH KATAKANA LETTER TI
  0xC2, 0xFF82, // HALFWIDTH KATAKANA LETTER TU
  0xC3, 0xFF83, // HALFWIDTH KATAKANA LETTER TE
  0xC4, 0xFF84, // HALFWIDTH KATAKANA LETTER TO
  0xC5, 0xFF85, // HALFWIDTH KATAKANA LETTER NA
  0xC6, 0xFF86, // HALFWIDTH KATAKANA LETTER NI
  0xC7, 0xFF87, // HALFWIDTH KATAKANA LETTER NU
  0xC8, 0xFF88, // HALFWIDTH KATAKANA LETTER NE
  0xC9, 0xFF89, // HALFWIDTH KATAKANA LETTER NO
  0xCA, 0xFF8A, // HALFWIDTH KATAKANA LETTER HA
  0xCB, 0xFF8B, // HALFWIDTH KATAKANA LETTER HI
  0xCC, 0xFF8C, // HALFWIDTH KATAKANA LETTER HU
  0xCD, 0xFF8D, // HALFWIDTH KATAKANA LETTER HE
  0xCE, 0xFF8E, // HALFWIDTH KATAKANA LETTER HO
  0xCF, 0xFF8F, // HALFWIDTH KATAKANA LETTER MA
  0xD0, 0xFF90, // HALFWIDTH KATAKANA LETTER MI
  0xD1, 0xFF91, // HALFWIDTH KATAKANA LETTER MU
  0xD2, 0xFF92, // HALFWIDTH KATAKANA LETTER ME
  0xD3, 0xFF93, // HALFWIDTH KATAKANA LETTER MO
  0xD4, 0xFF94, // HALFWIDTH KATAKANA LETTER YA
  0xD5, 0xFF95, // HALFWIDTH KATAKANA LETTER YU
  0xD6, 0xFF96, // HALFWIDTH KATAKANA LETTER YO
  0xD7, 0xFF97, // HALFWIDTH KATAKANA LETTER RA
  0xD8, 0xFF98, // HALFWIDTH KATAKANA LETTER RI
  0xD9, 0xFF99, // HALFWIDTH KATAKANA LETTER RU
  0xDA, 0xFF9A, // HALFWIDTH KATAKANA LETTER RE
  0xDB, 0xFF9B, // HALFWIDTH KATAKANA LETTER RO
  0xDC, 0xFF9C, // HALFWIDTH KATAKANA LETTER WA
  0xDD, 0xFF9D, // HALFWIDTH KATAKANA LETTER N
  0xDE, 0xFF9E, // HALFWIDTH KATAKANA VOICED SOUND MARK
  0xDF, 0xFF9F, // HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
  0x0000
};
